### PR TITLE
Community Templates: Adding new pipeline template for Azure Databricks.

### PR DESCRIPTION
**Pull request by guanjieshen**
Adding new templates for the following tasks:

- Trigger the execution of an existing Azure Databricks Workflow 
- Trigger an Azure Databricks notebook to run using Serverless Job Compute

### CODE REVIEW

**Comment by guanjieshen** [comment]
@microsoft-github-policy-service agree

**Comment by guanjieshen** [comment]
@fhljys would you be able to review this PR to add a new community template?

**Comment by guanjieshen** [comment]
@zhimadaren would you be able to review this PR to add a new community template?

**Comment by zhimadaren** [comment]
@n0elleli please take a look first

**Comment by guanjieshen** [comment]
Thanks @zhimadaren and @n0elleli for reviewing 🙏

**Comment by guanjieshen** [comment]
@n0elleli just checking in to see when you might get a change to review the PR.

**Comment by guanjieshen** [comment]
@zhimadaren and @n0elleli just wanted to check to see if there was time to review this PR?

**Comment by fhljys** [comment]
Hi @guanjieshen , sorry for the late response. Will get this closed by end of next week. Thanks.

**Pull request merged**
