### PR TITLE
ARM Templates for Delphix Data Compliance : Pipeline name update

### PR DESCRIPTION
**Pull request by akshay-dlpx**
### Changes 

- Sensitive Data Discovery with Delphix

      Name updated to : Sensitive Data Discovery with Delphix - Legacy
      Document link updated to :https://ecosystem.delphix.com/docs/main/sensitive-data-discovery-with-delphix

- Data Masking with Delphix

      Name updated to : Data masking with Delphix - Legacy
      Document link updated to : https://ecosystem.delphix.com/docs/main/data-masking-with-delphix

### Testing
These templates have been validated with Azure SQL DB as the source and Synapse as the target.

### CODE REVIEW

**Comment by akshay-dlpx** [comment]
Hi @nabhishek  and @zhimadaren,

I can see you reviewed and merged our prior PR - https://github.com/Azure/Azure-DataFactory/pull/536

Please review and merge this one or let us know the necessary next steps.

Thank you!

**Comment by akshay-dlpx** [comment]
Hi @nabhishek and @zhimadaren,

Can you please look into the changes, and help the PR get merged. 

You've merged our prior PR - https://github.com/Azure/Azure-DataFactory/pull/536

Thank you!

**Comment by zhimadaren** [comment]
Please reach out to Noelle li first and get it approved @akshay-dlpx

**Comment by akshay-dlpx** [comment]
@n0elleli please review the PR. 
[ Prior PR for reference - https://github.com/Azure/Azure-DataFactory/pull/536 ]

**Comment by zhimadaren** [comment]
@akshay-dlpx I will merge this pr and deploy it after my vacation, please expect next Sunday.

**Pull request merged**
